spring:
  application:
    name: book-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/books
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
